name: CI
description: Run tests and update documentation for the main branches.

on:
  push:
    branches:
      - "main"
      - "dev"

jobs:
  test:
    uses: ./.github/workflows/qa.yml

  docs:
    needs: test
    permissions: write-all
    uses: ./.github/workflows/docs.yml
