# Automatically perform all QA tasks - run linters, tests, etc.
name: Tests

on:
  push:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Install poe and pre-commit
        run: pip install poethepoet pre-commit

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # NOTE: using custom cache, to include pre-commit linters + deps
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: ${{ hashFiles('.pre-commit-config.yaml') }}-pre-commit

      - name: Check that all linters run without errors
        run: |
          poetry run poe lint --all-files

  test:
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Check that tests complete without errors
        run: |
          poetry install
          poetry run poe test
      - name: Check that documentation builds without errors
        run: |
          poetry install --with docs
          poetry run poe docs
      - name: Scan dependencies for known vulnerabilities
        run: |
          pipx install safety
          safety check -r pyproject.toml
